# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: deploy tutorial (only on push to main branch)
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
          fetch-depth: 0

    - name: set up Python
      uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # v4.3.0
      with:
        python-version: 3.8

    - name: install mkdocs
      run: |
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin
          mkdocs --version

    - name: build tutorial
      run: mkdocs build --strict && mkdocs gh-deploy --force
